id: twelve_column_fluid_standard
label: Twelve column fluid
type: equal_column
options:
  type: 'fluid'
  width: 100
  columns: 12
  padding_width: 1.5
  gutter_width: 2
  breakpoints:
    - 'module.rlayout.standard'

