id: three_column_fluid_smartphone
label: Three column fluid
type: equal_column
options:
  type: 'fluid'
  width: 100
  columns: 3
  padding_width: 1.5
  gutter_width: 2
  breakpoints:
    - 'module.rlayout.smartphone'

