id: six_column_fluid_tablet
label: Six column fluid
type: equal_column
options:
  type: 'fluid'
  width: 100
  columns: 6
  padding_width: 1.5
  gutter_width: 2
  breakpoints:
    - 'module.rlayout.tablet'

