id: default
label: Default layout
regions:
  - header_a
  - header_b
  - header_c
  - subheader_a
  - subheader_b
  - subheader_c
  - navigation
  - title
  - body
  - sidebar_a
  - sidebar_b
  - sidebar_c
  - footer_a
  - footer_b
  - footer_c
overrides:
